data:
  name: emoji
  type: image
  train_dir: data/emoji
  test_dir: data/emoji
  image_size: 32
  channels: 4
  n_labels: 9
network:
  class: ca_manifold
  kwargs:
    ds_size: 32
    n_filter: 32
    lat_size: 512
    n_calls: 4
    shared_params: False
    letter_encoding: True
    perception_noise: False
    fire_rate: 0.5
training:
  out_dir: save/emoji_s_ca_manifold_sto_letenc_persist_regen_nf32
  persistence: True
  regeneration: True
  batch_size: 64
  batch_split: 2
  batch_mult_steps: 4
  n_workers: 2
  optimizer: adamp
  lr: 0.0001
  equalize_lr: false
  n_epochs: 8192
  save_every: 1
  lr_anneal: 1.0
  lr_anneal_every: 0
  monitoring: tensorboard
  sample_every: 16
  sample_labels: 9